version: '3'
services:
  web:
    build: .
#    platform: linux/amd64
    #image: bitcoin_server_msa:latest
    environment:
      MONGODB_HOST: mongodb
      OPEN_AI_KEY: openAIKEY
      TZ: "Asia/Seoul"  # timezone 설정 부분
    command: python -u main.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongodb
    # networks:
    #   - likelion_default
  mongodb:
    image: mongo:4.4.6
#    platform: linux/amd64
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=AI
      - MONGO_INITDB_ROOT_USERNAME=USER_NAME
      - MONGO_INITDB_ROOT_PASSWORD=PASSWORD
    volumes:
      - .:/mongodb
    ports:
      - 27017:27017
#     networks:
#       - likelion_default
# networks:
#   likelion_default:
#     external: true